---
title: SS201
subtitle: Principles of Economics
author: MAJ Carson Homme
date: AY 23-2

bibliography: references.bib
bibstyle: spphys
# bibstyle options spbasic(default), spphys, spmpsci
output:
  pdf_document:
    citation_package: default
    latex_engine: xelatex
    toc: false
    number_sections: true
  geometry: margin=1in
  fontsize: 11pt
  compact-title: true
header-includes: 
  \usepackage{booktabs}
  \usepackage{tabularx}
  \usepackage{threeparttable}
  \usepackage{bm}
  \DeclareMathOperator{\Var}{Var}
  \usepackage{dcolumn}
  \usepackage{changepage}
  \usepackage{multirow}
  \usepackage[normalem]{ulem}
  \useunder{\uline}{\ul}{}
  \usepackage{fancyhdr}
  \AtBeginDocument{\let\maketitle\relax}
  
  # - \usepackage{xr} ## Needs .aux file which knitr automatically removes
  # - \externaldocument[SM-]{../SM/sceptic-SM}
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	cache = TRUE, 
	echo = FALSE, 
	warning = FALSE,
	message = FALSE,
	fig.align = 'center',
	out.width = '100%',
	dpi=300
	)
```

```{r libs, cache=FALSE, message=FALSE}
library(data.table)
library(ggplot2)
library(forcats)
library(kableExtra)
```


\fancyhf{}
\begin{center}
    \Large
    \textbf{
    \textit{SS201: Principles of Economics} \\ 
    AY 23-2 \\ 
    Lesson NO: \\ 
    }
\end{center}
\fancyfoot[C]{\thepage}

# Review {#sec:review}

So here;'s the deal 
sdafkja
kadsf

# Bottom Line Up Front {#sec:bluf}

# Lesson {#sec:lesson}
